# Generated by Django 5.2.6 on 2025-09-14 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capsules', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='capsule',
            old_name='content',
            new_name='message',
        ),
    ]
