# Generated by Django 5.2.6 on 2025-09-15 16:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsules', '0002_rename_content_capsule_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='capsule',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='capsule',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
